Update main.yml

diff --git a/Microservices/Chatgpt/.github/workflows/main.yml b/Microservices/Chatgpt/.github/workflows/main.yml
--- a/Microservices/Chatgpt/.github/workflows/main.yml
+++ b/Microservices/Chatgpt/.github/workflows/main.yml
@@ -38,6 +38,18 @@ jobs:
           docker build -t advancedswe.azurecr.io/chatgpt:latest .
           docker push advancedswe.azurecr.io/chatgpt:latest
 
+      # Delete untagged manifests after pushing the new image
+      - name: Delete All Untagged Manifests
+        run: |
+          # List all untagged manifests (digests) in the repository
+          untagged_manifests=$(az acr repository show-manifests --name AdvancedSWE --repository chatgpt --output tsv --query "[?tags == null].digest")
+
+          # Loop through each untagged manifest and delete it
+          for digest in $untagged_manifests; do
+            echo "Deleting untagged image with digest: $digest in repository: chatgpt"
+            az acr repository delete --name AdvancedSWE --repository chatgpt --manifest $digest --yes || echo "Failed to delete untagged image with digest: $digest"
+          done
+
       - name: Log in to Azure
         uses: azure/login@v1
         with:
